# Generated by Django 2.2.5 on 2019-10-02 12:55

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(max_length=200)),
                ('cover', models.ImageField(default='defaultevent.jpg', upload_to=events.models.user_directory_path)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField()),
                ('scheduled_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Draft'), (2, 'Withdrawn')], default=1)),
                ('slug', models.SlugField(help_text='WARNING : Use the same slug for while creating a BLOG Post about events', max_length=200, unique=True)),
                ('website', models.URLField(blank=True, default='https://exampleeventwebsite.com')),
                ('eventtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventCategory')),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
