# Generated by Django 2.2.5 on 2019-10-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
