# Generated by Django 2.2.5 on 2019-10-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
