# Generated by Django 2.2.5 on 2019-10-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191003_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maplink',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
