# Generated by Django 2.2.5 on 2019-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Member'), (1, 'Volunteer'), (2, 'Team Lead'), (3, 'Admin')], default=0),
        ),
    ]
