# Generated by Django 2.2.5 on 2019-10-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work',
            field=models.CharField(blank=True, default='Student', help_text='eg:- Web Developer, Architect', max_length=30),
        ),
    ]
