# Generated by Django 2.2.5 on 2019-10-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191005_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDSChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('location', models.CharField(blank=True, default='ND', help_text='eg:- College Name, organization name ..etc', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Chapter',
            },
        ),
    ]
