# Generated by Django 2.2.5 on 2019-10-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sdschapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.SDSChapter'),
        ),
    ]
