# Generated by Django 2.2.5 on 2019-10-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_stackoverflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Member'), (1, 'Volunteer'), (2, 'Team Lead'), (3, 'Admin'), (4, 'Editor'), (5, 'Publisher'), (6, 'EventManager'), (7, 'Event+Publisher')], default=0),
        ),
    ]
