# Generated by Django 2.2.5 on 2019-10-06 08:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slidercover',
            field=models.ImageField(default='default.png', upload_to=blog.models.user_directory_path_slider),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='default.png', upload_to=blog.models.user_directory_path),
        ),
    ]
