# Generated by Django 2.2.5 on 2019-10-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_sliderpos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sliderpos',
            field=models.IntegerField(choices=[(2, 'None'), (1, 'Other'), (0, 'First')], default=2),
        ),
    ]
