# Generated by Django 2.2.5 on 2019-10-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191007_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sliderpos',
            field=models.IntegerField(choices=[(1, 'Other'), (2, 'None'), (0, 'First')], default=2),
        ),
    ]
