# Generated by Django 2.2.5 on 2019-10-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191009_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sliderpos',
            field=models.IntegerField(choices=[(0, 'First'), (2, 'None'), (1, 'Other')], default=2),
        ),
    ]
