# Generated by Django 2.2.5 on 2019-10-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191005_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sds_response', models.IntegerField(choices=[(0, 'NOT RESPONDED'), (1, 'RESPONDED'), (2, 'SPAM')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'contact',
            },
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name_plural': 'Project Categories'},
        ),
    ]
